# Read the Docs configuration file for Flowrra
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      # Generate API documentation before building
      - sphinx-apidoc -f -o sphinx-docs/source/api src/flowrra

sphinx:
  configuration: sphinx-docs/source/conf.py
  fail_on_warning: false

python:
  install:
    # Install the package itself
    - method: pip
      path: .
    # Install documentation dependencies
    - requirements: sphinx-docs/requirements.txt
